- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Remove OVS DB Content
    shell: rm -rf /var/lib/openvswitch/ovn*.db
  - name: Remove any old ovn-kubernets
    shell: rm -r -f ~/ovn-kubernetes
  - name: Clone ovn-kubernetes
    shell: git clone https://github.com/openvswitch/ovn-kubernetes ~/ovn-kubernetes
  - name: Provision the OVN Namespace
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovn-namespace.yaml
    ignore_errors: yes
  - name: Provision the OVN Policy
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovn-policy.yaml
    ignore_errors: yes
  - name: Provision the OVN Project
    shell: oc project ovn-kubernetes
    ignore_errors: yes
  - name: Add adm policy auyuid
    shell: oc adm policy add-scc-to-user anyuid -z ovn
    ignore_errors: yes
  - name: Run the ovn-setup
    shell: ./ovn-kubernetes/dist/ansible/scripts/ovn-setup.sh
    ignore_errors: yes
  - name: Start the ovn-ovs daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/sdn-ovs.yaml
    ignore_errors: yes
  - name: Start the master ovn daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovnkube-master.yaml
    ignore_errors: yes
  - name: Start the node ovn daemonset
    shell: oc create -f ~/ovn-kubernetes/dist/yaml/ovnkube.yaml
    ignore_errors: yes
