- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Create destination directory
    file: path=/opt/cni/bin state=directory
  - name: Create directory for cni plugins
    file: path=/tmp/cniplugin state=directory
  - name: Get cni plugins
    shell: wget -q https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz; tar xvzf cni-plugins-amd64-v0.7.1.tgz -C /tmp/cniplugin
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: Create /opt/cni/bin
    file: path=/opt/cni/bin state=directory
  - name: Push the cni loopback plugin to all nodes
    copy:
      src: /tmp/cniplugin/loopback
      dest: /opt/cni/bin/loopback
      mode: u+rwx
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
  - name: open firewall 6641
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6641 -j ACCEPT
  - name: open firewall 6642
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6642 -j ACCEPT
  - name: open firewall 6081
    shell: iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 6081 -j ACCEPT
  - name: Save iptables rules
    shell: service iptables save
